import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";

function CertificatePage() {
  const { attemptId } = useParams();
  const [cert, setCert] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem("token");
    fetch(`/api/certificate/attempt/${attemptId}`, {
      headers: { "Authorization": `Bearer ${token}` }
    })
    .then(res => res.json())
    .then(data => {
      setCert(data);
      setLoading(false);
    })
    .catch(err => {
      console.error(err);
      setLoading(false);
    });
  }, [attemptId]);

  if (loading) return <h2>Loading Certificate...</h2>;
  if (!cert || cert.message) return <h2>Certificate Not Found</h2>;

  return (
    <div style={{ padding: "40px", fontFamily: "sans-serif", textAlign: "center", background: "#f4f4f9", minHeight: "100vh" }}>
      <div style={{ 
        maxWidth: "800px", margin: "0 auto", background: "white", padding: "40px", 
        border: "10px solid #d4af37", borderRadius: "10px", boxShadow: "0 0 15px rgba(0,0,0,0.2)"
       }}>
        <h1 style={{fontSize: "48px", color: "#333"}}>Certificate of Completion</h1>
        <p style={{fontSize: "20px", marginTop: "20px"}}>This is to certify that</p>
        <h2 style={{fontSize: "36px", color: "#007bff", textDecoration: "underline"}}>{cert.student?.fullName || "Student"}</h2>
        <p style={{fontSize: "20px"}}>has successfully completed the exam</p>
        <h2 style={{fontSize: "32px", color: "#555"}}>{cert.exam?.title || "Exam"}</h2>
        <p style={{fontSize: "18px", marginTop: "30px"}}>Issued on: {new Date(cert.issueDate).toLocaleDateString()}</p>
        
        <div style={{marginTop: "50px", textAlign: "center"}}>
          <p style={{fontSize: "16px", opacity: 0.8, marginTop: "20px"}}>Certificate ID: {cert._id}</p>
          <p style={{fontSize: "14px", opacity: 0.6, marginTop: "10px"}}>Generated by Exam Portal System</p>
        </div>
      </div>
      <button onClick={() => window.print()} style={{marginTop: "20px", padding: "10px 20px", fontSize: "16px", cursor: "pointer", background: "#007bff", color: "white", border: "none", borderRadius: "5px"}}>
        ⬇️ Download / Print Certificate
      </button>
    </div>
  );
}

export default CertificatePage;
